version: '3.8'

services:
    #  axiston-gateway:
    #    container_name: gateway
    #    build:
    #      context: ./
    #      dockerfile: Dockerfile
    #    environment:
    #      - DATABASE=postgresql://usr:pwd@localhost:5432/db
    #    depends_on:
    #      - axiston-database
    #    ports:
    #      - "8000:8000"
    #    networks:
    #      - axiston

    # https://hub.docker.com/u/axiston
    axiston-database:
        container_name: database
        build:
            context: ./postgres/
            dockerfile: ./Dockerfile
        environment:
            POSTGRES_USER: usr
            POSTGRES_PASSWORD: pwd
            POSTGRES_DB: db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - axiston

volumes:
    pgdata:

networks:
    axiston:
